### ISSUE TITLE
Allow admin-user to create event from the application easily

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/eventus#139]
### Todo

Step 1:
- [ ] create a `role` column in the user database
- [ ] set @S-Stanley account as admin user
- [ ] create a GET /users/:user_id endpoint to fetch data about a specific users, including is `role`

Step 2:
- [ ] create a GET endpoint to fetch all hosts with their available activities
- [ ] show a button on the event-view page only visible by admin users to create an event
- [ ] create an event-new page allowing admin-user to create events

### Issue lifecycle
- [x] Feature specifities.
- [x] Tech specifities.

**Comment by S-Stanley** [comment]
```bash
curl https://api.sakafet.fr/users/{user_id}/role -d role=ADMIN
```
