### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/eventus#169]
### Solution proposed

Allow users to subscribe to communities (e.g programming, students, etc). Communities have a name and a location (city). They also have members.

### Todo

- [ ] Create collection communities
- [ ] Create collection community_members (or members)
- [ ] Create POST /communities
- [ ] Create GET /communities
- [ ] Create POST /communities/members
- [ ] Create GET /communities/members
- [ ] Create the community list page on the front-end
- [ ] Update events to be related to communities
- [ ] Add community settings in the settings screen

### Issue lifecycle
- [ ] Feature specifities.
- [ ] Tech specifities.
